services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GMED
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
